// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/nlmixr2est.h"
#include "../inst/include/nlmixr2est_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cholSE_
NumericMatrix cholSE_(NumericMatrix A, double tol);
RcppExport SEXP _nlmixr2est_cholSE_(SEXP ASEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(cholSE_(A, tol));
    return rcpp_result_gen;
END_RCPP
}
// nlmixrExpandFdParNlme_
List nlmixrExpandFdParNlme_(CharacterVector state, CharacterVector vars);
static SEXP _nlmixr2est_nlmixrExpandFdParNlme__try(SEXP stateSEXP, SEXP varsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type vars(varsSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmixrExpandFdParNlme_(state, vars));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _nlmixr2est_nlmixrExpandFdParNlme_(SEXP stateSEXP, SEXP varsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_nlmixr2est_nlmixrExpandFdParNlme__try(stateSEXP, varsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// filterNormalLikeAndDoses
List filterNormalLikeAndDoses(IntegerVector& inCmt, IntegerVector& inDistribution, IntegerVector& inDistCmt);
RcppExport SEXP _nlmixr2est_filterNormalLikeAndDoses(SEXP inCmtSEXP, SEXP inDistributionSEXP, SEXP inDistCmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector& >::type inCmt(inCmtSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type inDistribution(inDistributionSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type inDistCmt(inDistCmtSEXP);
    rcpp_result_gen = Rcpp::wrap(filterNormalLikeAndDoses(inCmt, inDistribution, inDistCmt));
    return rcpp_result_gen;
END_RCPP
}
// rxode2hasLlik
LogicalVector rxode2hasLlik();
RcppExport SEXP _nlmixr2est_rxode2hasLlik() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rxode2hasLlik());
    return rcpp_result_gen;
END_RCPP
}
// censNormalPartials_
arma::mat censNormalPartials_(const arma::ivec& cens, const arma::vec& dv, const arma::vec& lim, const arma::vec& fv, const arma::vec& rv, int order);
RcppExport SEXP _nlmixr2est_censNormalPartials_(SEXP censSEXP, SEXP dvSEXP, SEXP limSEXP, SEXP fvSEXP, SEXP rvSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::ivec& >::type cens(censSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dv(dvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lim(limSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fv(fvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rv(rvSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(censNormalPartials_(cens, dv, lim, fv, rv, order));
    return rcpp_result_gen;
END_RCPP
}
// foceiSubjectGradFocei_
Rcpp::List foceiSubjectGradFocei_(const arma::mat& a, const arma::cube& A, const arma::vec& r1, const arma::vec& r2, const arma::vec& p, const arma::vec& p1, const arma::mat& perRf, const arma::mat& perPs, const arma::mat& perRs, const arma::vec& ehat, const arma::mat& Oi, const arma::cube& dOiEst, const arma::vec& tr28, int neta, int nth, int nsg, int nom, const arma::ivec& dirTh);
RcppExport SEXP _nlmixr2est_foceiSubjectGradFocei_(SEXP aSEXP, SEXP ASEXP, SEXP r1SEXP, SEXP r2SEXP, SEXP pSEXP, SEXP p1SEXP, SEXP perRfSEXP, SEXP perPsSEXP, SEXP perRsSEXP, SEXP ehatSEXP, SEXP OiSEXP, SEXP dOiEstSEXP, SEXP tr28SEXP, SEXP netaSEXP, SEXP nthSEXP, SEXP nsgSEXP, SEXP nomSEXP, SEXP dirThSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type perRf(perRfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type perPs(perPsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type perRs(perRsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ehat(ehatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Oi(OiSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dOiEst(dOiEstSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tr28(tr28SEXP);
    Rcpp::traits::input_parameter< int >::type neta(netaSEXP);
    Rcpp::traits::input_parameter< int >::type nth(nthSEXP);
    Rcpp::traits::input_parameter< int >::type nsg(nsgSEXP);
    Rcpp::traits::input_parameter< int >::type nom(nomSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type dirTh(dirThSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiSubjectGradFocei_(a, A, r1, r2, p, p1, perRf, perPs, perRs, ehat, Oi, dOiEst, tr28, neta, nth, nsg, nom, dirTh));
    return rcpp_result_gen;
END_RCPP
}
// foceiSubjectGradFR_
Rcpp::List foceiSubjectGradFR_(const arma::mat& a, const arma::cube& A, const arma::mat& aR, const arma::cube& AR, const arma::mat& Rsig, const arma::cube& RsigDir, const arma::mat& dvSens, const arma::ivec& censv, const arma::vec& limv, int censOpt, const arma::vec& fv, const arma::vec& yv, const arma::vec& Rv, const arma::vec& ehat, const arma::mat& Oi, const arma::cube& dOiEst, const arma::vec& tr28, int neta, int nth, int nsg, int nom, const arma::ivec& dirTh, const arma::ivec& sigCol);
RcppExport SEXP _nlmixr2est_foceiSubjectGradFR_(SEXP aSEXP, SEXP ASEXP, SEXP aRSEXP, SEXP ARSEXP, SEXP RsigSEXP, SEXP RsigDirSEXP, SEXP dvSensSEXP, SEXP censvSEXP, SEXP limvSEXP, SEXP censOptSEXP, SEXP fvSEXP, SEXP yvSEXP, SEXP RvSEXP, SEXP ehatSEXP, SEXP OiSEXP, SEXP dOiEstSEXP, SEXP tr28SEXP, SEXP netaSEXP, SEXP nthSEXP, SEXP nsgSEXP, SEXP nomSEXP, SEXP dirThSEXP, SEXP sigColSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aR(aRSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type AR(ARSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Rsig(RsigSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type RsigDir(RsigDirSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dvSens(dvSensSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type censv(censvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type limv(limvSEXP);
    Rcpp::traits::input_parameter< int >::type censOpt(censOptSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fv(fvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yv(yvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Rv(RvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ehat(ehatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Oi(OiSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dOiEst(dOiEstSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tr28(tr28SEXP);
    Rcpp::traits::input_parameter< int >::type neta(netaSEXP);
    Rcpp::traits::input_parameter< int >::type nth(nthSEXP);
    Rcpp::traits::input_parameter< int >::type nsg(nsgSEXP);
    Rcpp::traits::input_parameter< int >::type nom(nomSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type dirTh(dirThSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type sigCol(sigColSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiSubjectGradFR_(a, A, aR, AR, Rsig, RsigDir, dvSens, censv, limv, censOpt, fv, yv, Rv, ehat, Oi, dOiEst, tr28, neta, nth, nsg, nom, dirTh, sigCol));
    return rcpp_result_gen;
END_RCPP
}
// foceiGradAllFR_
Rcpp::List foceiGradAllFR_(const arma::mat& a, const arma::cube& A, const arma::mat& aR, const arma::cube& AR, const arma::mat& Rsig, const arma::cube& RsigDir, const arma::mat& dvSens, const arma::ivec& censv, const arma::vec& limv, int censOpt, const arma::vec& fv, const arma::vec& yv, const arma::vec& Rv, const arma::mat& ehat, const arma::ivec& obsOffset, const arma::mat& Oi, const arma::cube& dOiEst, const arma::vec& tr28, int neta, int nth, int nsg, int nom, const arma::ivec& dirTh, const arma::ivec& sigCol, int ncores);
RcppExport SEXP _nlmixr2est_foceiGradAllFR_(SEXP aSEXP, SEXP ASEXP, SEXP aRSEXP, SEXP ARSEXP, SEXP RsigSEXP, SEXP RsigDirSEXP, SEXP dvSensSEXP, SEXP censvSEXP, SEXP limvSEXP, SEXP censOptSEXP, SEXP fvSEXP, SEXP yvSEXP, SEXP RvSEXP, SEXP ehatSEXP, SEXP obsOffsetSEXP, SEXP OiSEXP, SEXP dOiEstSEXP, SEXP tr28SEXP, SEXP netaSEXP, SEXP nthSEXP, SEXP nsgSEXP, SEXP nomSEXP, SEXP dirThSEXP, SEXP sigColSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aR(aRSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type AR(ARSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Rsig(RsigSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type RsigDir(RsigDirSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dvSens(dvSensSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type censv(censvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type limv(limvSEXP);
    Rcpp::traits::input_parameter< int >::type censOpt(censOptSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fv(fvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yv(yvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Rv(RvSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ehat(ehatSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type obsOffset(obsOffsetSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Oi(OiSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dOiEst(dOiEstSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tr28(tr28SEXP);
    Rcpp::traits::input_parameter< int >::type neta(netaSEXP);
    Rcpp::traits::input_parameter< int >::type nth(nthSEXP);
    Rcpp::traits::input_parameter< int >::type nsg(nsgSEXP);
    Rcpp::traits::input_parameter< int >::type nom(nomSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type dirTh(dirThSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type sigCol(sigColSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiGradAllFR_(a, A, aR, AR, Rsig, RsigDir, dvSens, censv, limv, censOpt, fv, yv, Rv, ehat, obsOffset, Oi, dOiEst, tr28, neta, nth, nsg, nom, dirTh, sigCol, ncores));
    return rcpp_result_gen;
END_RCPP
}
// foceiSubjectGradFoceFR_
Rcpp::List foceiSubjectGradFoceFR_(const arma::mat& a, const arma::cube& A, const arma::mat& aRe, const arma::mat& aRc, const arma::mat& R0sig, const arma::mat& dvSens, const arma::ivec& censv, const arma::vec& limv, const arma::vec& fv, const arma::vec& yv, const arma::vec& R0v, const arma::vec& ehat, const arma::mat& Oi, const arma::cube& dOiEst, const arma::vec& tr28, int neta, int nth, int nsg, int nom, const arma::ivec& dirTh, const arma::ivec& sigCol, int fp);
RcppExport SEXP _nlmixr2est_foceiSubjectGradFoceFR_(SEXP aSEXP, SEXP ASEXP, SEXP aReSEXP, SEXP aRcSEXP, SEXP R0sigSEXP, SEXP dvSensSEXP, SEXP censvSEXP, SEXP limvSEXP, SEXP fvSEXP, SEXP yvSEXP, SEXP R0vSEXP, SEXP ehatSEXP, SEXP OiSEXP, SEXP dOiEstSEXP, SEXP tr28SEXP, SEXP netaSEXP, SEXP nthSEXP, SEXP nsgSEXP, SEXP nomSEXP, SEXP dirThSEXP, SEXP sigColSEXP, SEXP fpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aRe(aReSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aRc(aRcSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R0sig(R0sigSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dvSens(dvSensSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type censv(censvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type limv(limvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fv(fvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yv(yvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type R0v(R0vSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ehat(ehatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Oi(OiSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dOiEst(dOiEstSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tr28(tr28SEXP);
    Rcpp::traits::input_parameter< int >::type neta(netaSEXP);
    Rcpp::traits::input_parameter< int >::type nth(nthSEXP);
    Rcpp::traits::input_parameter< int >::type nsg(nsgSEXP);
    Rcpp::traits::input_parameter< int >::type nom(nomSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type dirTh(dirThSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type sigCol(sigColSEXP);
    Rcpp::traits::input_parameter< int >::type fp(fpSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiSubjectGradFoceFR_(a, A, aRe, aRc, R0sig, dvSens, censv, limv, fv, yv, R0v, ehat, Oi, dOiEst, tr28, neta, nth, nsg, nom, dirTh, sigCol, fp));
    return rcpp_result_gen;
END_RCPP
}
// foceiGradAllFoceFR_
Rcpp::List foceiGradAllFoceFR_(const arma::mat& a, const arma::cube& A, const arma::mat& aRe, const arma::mat& aRc, const arma::mat& R0sig, const arma::mat& dvSens, const arma::ivec& censv, const arma::vec& limv, const arma::vec& fv, const arma::vec& yv, const arma::vec& R0v, const arma::mat& ehat, const arma::ivec& obsOffset, const arma::mat& Oi, const arma::cube& dOiEst, const arma::vec& tr28, int neta, int nth, int nsg, int nom, const arma::ivec& dirTh, const arma::ivec& sigCol, int fp, int ncores);
RcppExport SEXP _nlmixr2est_foceiGradAllFoceFR_(SEXP aSEXP, SEXP ASEXP, SEXP aReSEXP, SEXP aRcSEXP, SEXP R0sigSEXP, SEXP dvSensSEXP, SEXP censvSEXP, SEXP limvSEXP, SEXP fvSEXP, SEXP yvSEXP, SEXP R0vSEXP, SEXP ehatSEXP, SEXP obsOffsetSEXP, SEXP OiSEXP, SEXP dOiEstSEXP, SEXP tr28SEXP, SEXP netaSEXP, SEXP nthSEXP, SEXP nsgSEXP, SEXP nomSEXP, SEXP dirThSEXP, SEXP sigColSEXP, SEXP fpSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aRe(aReSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aRc(aRcSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R0sig(R0sigSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dvSens(dvSensSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type censv(censvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type limv(limvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fv(fvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yv(yvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type R0v(R0vSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ehat(ehatSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type obsOffset(obsOffsetSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Oi(OiSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dOiEst(dOiEstSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tr28(tr28SEXP);
    Rcpp::traits::input_parameter< int >::type neta(netaSEXP);
    Rcpp::traits::input_parameter< int >::type nth(nthSEXP);
    Rcpp::traits::input_parameter< int >::type nsg(nsgSEXP);
    Rcpp::traits::input_parameter< int >::type nom(nomSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type dirTh(dirThSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type sigCol(sigColSEXP);
    Rcpp::traits::input_parameter< int >::type fp(fpSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiGradAllFoceFR_(a, A, aRe, aRc, R0sig, dvSens, censv, limv, fv, yv, R0v, ehat, obsOffset, Oi, dOiEst, tr28, neta, nth, nsg, nom, dirTh, sigCol, fp, ncores));
    return rcpp_result_gen;
END_RCPP
}
// foceiSubjectRFR_
arma::mat foceiSubjectRFR_(const arma::mat& a, const arma::cube& A, const arma::cube& Ath, const arma::mat& aR, const arma::cube& AR, const arma::cube& AthR, const arma::mat& dvSens, const arma::mat& dvSens2, const arma::ivec& censv, const arma::vec& limv, const arma::vec& fv, const arma::vec& yv, const arma::vec& Rv, const arma::vec& ehat, const arma::mat& Oi, const arma::cube& dOi, const arma::cube& d2Oi, const arma::mat& d2LD, int neta, int ndir, int ndirP, int nom, const arma::ivec& dirP);
RcppExport SEXP _nlmixr2est_foceiSubjectRFR_(SEXP aSEXP, SEXP ASEXP, SEXP AthSEXP, SEXP aRSEXP, SEXP ARSEXP, SEXP AthRSEXP, SEXP dvSensSEXP, SEXP dvSens2SEXP, SEXP censvSEXP, SEXP limvSEXP, SEXP fvSEXP, SEXP yvSEXP, SEXP RvSEXP, SEXP ehatSEXP, SEXP OiSEXP, SEXP dOiSEXP, SEXP d2OiSEXP, SEXP d2LDSEXP, SEXP netaSEXP, SEXP ndirSEXP, SEXP ndirPSEXP, SEXP nomSEXP, SEXP dirPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Ath(AthSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aR(aRSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type AR(ARSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type AthR(AthRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dvSens(dvSensSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dvSens2(dvSens2SEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type censv(censvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type limv(limvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fv(fvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yv(yvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Rv(RvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ehat(ehatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Oi(OiSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dOi(dOiSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type d2Oi(d2OiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type d2LD(d2LDSEXP);
    Rcpp::traits::input_parameter< int >::type neta(netaSEXP);
    Rcpp::traits::input_parameter< int >::type ndir(ndirSEXP);
    Rcpp::traits::input_parameter< int >::type ndirP(ndirPSEXP);
    Rcpp::traits::input_parameter< int >::type nom(nomSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type dirP(dirPSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiSubjectRFR_(a, A, Ath, aR, AR, AthR, dvSens, dvSens2, censv, limv, fv, yv, Rv, ehat, Oi, dOi, d2Oi, d2LD, neta, ndir, ndirP, nom, dirP));
    return rcpp_result_gen;
END_RCPP
}
// foceiRAllFR_
arma::mat foceiRAllFR_(const arma::mat& a, const arma::cube& A, const arma::cube& Ath, const arma::mat& aR, const arma::cube& AR, const arma::cube& AthR, const arma::mat& dvSens, const arma::mat& dvSens2, const arma::ivec& censv, const arma::vec& limv, const arma::vec& fv, const arma::vec& yv, const arma::vec& Rv, const arma::mat& ehat, const arma::ivec& obsOffset, const arma::mat& Oi, const arma::cube& dOi, const arma::cube& d2Oi, const arma::mat& d2LD, int neta, int ndir, int ndirP, int nom, const arma::ivec& dirP, int ncores);
RcppExport SEXP _nlmixr2est_foceiRAllFR_(SEXP aSEXP, SEXP ASEXP, SEXP AthSEXP, SEXP aRSEXP, SEXP ARSEXP, SEXP AthRSEXP, SEXP dvSensSEXP, SEXP dvSens2SEXP, SEXP censvSEXP, SEXP limvSEXP, SEXP fvSEXP, SEXP yvSEXP, SEXP RvSEXP, SEXP ehatSEXP, SEXP obsOffsetSEXP, SEXP OiSEXP, SEXP dOiSEXP, SEXP d2OiSEXP, SEXP d2LDSEXP, SEXP netaSEXP, SEXP ndirSEXP, SEXP ndirPSEXP, SEXP nomSEXP, SEXP dirPSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Ath(AthSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aR(aRSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type AR(ARSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type AthR(AthRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dvSens(dvSensSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dvSens2(dvSens2SEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type censv(censvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type limv(limvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fv(fvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yv(yvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Rv(RvSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ehat(ehatSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type obsOffset(obsOffsetSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Oi(OiSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dOi(dOiSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type d2Oi(d2OiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type d2LD(d2LDSEXP);
    Rcpp::traits::input_parameter< int >::type neta(netaSEXP);
    Rcpp::traits::input_parameter< int >::type ndir(ndirSEXP);
    Rcpp::traits::input_parameter< int >::type ndirP(ndirPSEXP);
    Rcpp::traits::input_parameter< int >::type nom(nomSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type dirP(dirPSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiRAllFR_(a, A, Ath, aR, AR, AthR, dvSens, dvSens2, censv, limv, fv, yv, Rv, ehat, obsOffset, Oi, dOi, d2Oi, d2LD, neta, ndir, ndirP, nom, dirP, ncores));
    return rcpp_result_gen;
END_RCPP
}
// foceiSubjectRfoceFR_
arma::mat foceiSubjectRfoceFR_(const arma::mat& a, const arma::cube& A, const arma::cube& Ath, const arma::mat& aRe, const arma::mat& aRc, const arma::cube& ARe, const arma::cube& ARc, const arma::mat& dvSens, const arma::mat& dvSens2, const arma::ivec& censv, const arma::vec& limv, const arma::vec& fv, const arma::vec& yv, const arma::vec& R0v, const arma::vec& ehat, const arma::mat& Oi, const arma::cube& dOi, const arma::cube& d2Oi, const arma::mat& d2LD, int neta, int ndir, int ndirP, int nom, const arma::ivec& dirP);
RcppExport SEXP _nlmixr2est_foceiSubjectRfoceFR_(SEXP aSEXP, SEXP ASEXP, SEXP AthSEXP, SEXP aReSEXP, SEXP aRcSEXP, SEXP AReSEXP, SEXP ARcSEXP, SEXP dvSensSEXP, SEXP dvSens2SEXP, SEXP censvSEXP, SEXP limvSEXP, SEXP fvSEXP, SEXP yvSEXP, SEXP R0vSEXP, SEXP ehatSEXP, SEXP OiSEXP, SEXP dOiSEXP, SEXP d2OiSEXP, SEXP d2LDSEXP, SEXP netaSEXP, SEXP ndirSEXP, SEXP ndirPSEXP, SEXP nomSEXP, SEXP dirPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Ath(AthSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aRe(aReSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aRc(aRcSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type ARe(AReSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type ARc(ARcSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dvSens(dvSensSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dvSens2(dvSens2SEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type censv(censvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type limv(limvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fv(fvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yv(yvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type R0v(R0vSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ehat(ehatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Oi(OiSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dOi(dOiSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type d2Oi(d2OiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type d2LD(d2LDSEXP);
    Rcpp::traits::input_parameter< int >::type neta(netaSEXP);
    Rcpp::traits::input_parameter< int >::type ndir(ndirSEXP);
    Rcpp::traits::input_parameter< int >::type ndirP(ndirPSEXP);
    Rcpp::traits::input_parameter< int >::type nom(nomSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type dirP(dirPSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiSubjectRfoceFR_(a, A, Ath, aRe, aRc, ARe, ARc, dvSens, dvSens2, censv, limv, fv, yv, R0v, ehat, Oi, dOi, d2Oi, d2LD, neta, ndir, ndirP, nom, dirP));
    return rcpp_result_gen;
END_RCPP
}
// foceiRAllFoceFR_
arma::mat foceiRAllFoceFR_(const arma::mat& a, const arma::cube& A, const arma::cube& Ath, const arma::mat& aRe, const arma::mat& aRc, const arma::cube& ARe, const arma::cube& ARc, const arma::mat& dvSens, const arma::mat& dvSens2, const arma::ivec& censv, const arma::vec& limv, const arma::vec& fv, const arma::vec& yv, const arma::vec& R0v, const arma::mat& ehat, const arma::ivec& obsOffset, const arma::mat& Oi, const arma::cube& dOi, const arma::cube& d2Oi, const arma::mat& d2LD, int neta, int ndir, int ndirP, int nom, const arma::ivec& dirP, int ncores);
RcppExport SEXP _nlmixr2est_foceiRAllFoceFR_(SEXP aSEXP, SEXP ASEXP, SEXP AthSEXP, SEXP aReSEXP, SEXP aRcSEXP, SEXP AReSEXP, SEXP ARcSEXP, SEXP dvSensSEXP, SEXP dvSens2SEXP, SEXP censvSEXP, SEXP limvSEXP, SEXP fvSEXP, SEXP yvSEXP, SEXP R0vSEXP, SEXP ehatSEXP, SEXP obsOffsetSEXP, SEXP OiSEXP, SEXP dOiSEXP, SEXP d2OiSEXP, SEXP d2LDSEXP, SEXP netaSEXP, SEXP ndirSEXP, SEXP ndirPSEXP, SEXP nomSEXP, SEXP dirPSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Ath(AthSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aRe(aReSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aRc(aRcSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type ARe(AReSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type ARc(ARcSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dvSens(dvSensSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dvSens2(dvSens2SEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type censv(censvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type limv(limvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fv(fvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yv(yvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type R0v(R0vSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ehat(ehatSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type obsOffset(obsOffsetSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Oi(OiSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type dOi(dOiSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type d2Oi(d2OiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type d2LD(d2LDSEXP);
    Rcpp::traits::input_parameter< int >::type neta(netaSEXP);
    Rcpp::traits::input_parameter< int >::type ndir(ndirSEXP);
    Rcpp::traits::input_parameter< int >::type ndirP(ndirPSEXP);
    Rcpp::traits::input_parameter< int >::type nom(nomSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type dirP(dirPSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiRAllFoceFR_(a, A, Ath, aRe, aRc, ARe, ARc, dvSens, dvSens2, censv, limv, fv, yv, R0v, ehat, obsOffset, Oi, dOi, d2Oi, d2LD, neta, ndir, ndirP, nom, dirP, ncores));
    return rcpp_result_gen;
END_RCPP
}
// freeFocei
void freeFocei();
RcppExport SEXP _nlmixr2est_freeFocei() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    freeFocei();
    return R_NilValue;
END_RCPP
}
// foceiInnerLp
NumericVector foceiInnerLp(NumericVector eta, int id);
RcppExport SEXP _nlmixr2est_foceiInnerLp(SEXP etaSEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiInnerLp(eta, id));
    return rcpp_result_gen;
END_RCPP
}
// likInner
double likInner(NumericVector eta, int id);
RcppExport SEXP _nlmixr2est_likInner(SEXP etaSEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(likInner(eta, id));
    return rcpp_result_gen;
END_RCPP
}
// foceiLik
double foceiLik(NumericVector theta);
RcppExport SEXP _nlmixr2est_foceiLik(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiLik(theta));
    return rcpp_result_gen;
END_RCPP
}
// foceiOfv
double foceiOfv(NumericVector theta);
RcppExport SEXP _nlmixr2est_foceiOfv(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiOfv(theta));
    return rcpp_result_gen;
END_RCPP
}
// foceiNumericGrad
NumericVector foceiNumericGrad(NumericVector theta);
RcppExport SEXP _nlmixr2est_foceiNumericGrad(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiNumericGrad(theta));
    return rcpp_result_gen;
END_RCPP
}
// foceiSetup_
NumericVector foceiSetup_(const RObject& obj, const RObject& data, NumericVector theta, IntegerVector mixIdx, Nullable<LogicalVector> thetaFixed, Nullable<LogicalVector> skipCov, RObject rxInv, Nullable<NumericVector> lower, Nullable<NumericVector> upper, Nullable<NumericMatrix> etaMat, Nullable<List> control);
RcppExport SEXP _nlmixr2est_foceiSetup_(SEXP objSEXP, SEXP dataSEXP, SEXP thetaSEXP, SEXP mixIdxSEXP, SEXP thetaFixedSEXP, SEXP skipCovSEXP, SEXP rxInvSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP etaMatSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const RObject& >::type obj(objSEXP);
    Rcpp::traits::input_parameter< const RObject& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mixIdx(mixIdxSEXP);
    Rcpp::traits::input_parameter< Nullable<LogicalVector> >::type thetaFixed(thetaFixedSEXP);
    Rcpp::traits::input_parameter< Nullable<LogicalVector> >::type skipCov(skipCovSEXP);
    Rcpp::traits::input_parameter< RObject >::type rxInv(rxInvSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type etaMat(etaMatSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiSetup_(obj, data, theta, mixIdx, thetaFixed, skipCov, rxInv, lower, upper, etaMat, control));
    return rcpp_result_gen;
END_RCPP
}
// foceiOuterF
double foceiOuterF(NumericVector& theta);
RcppExport SEXP _nlmixr2est_foceiOuterF(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiOuterF(theta));
    return rcpp_result_gen;
END_RCPP
}
// foceiOuterG
NumericVector foceiOuterG(NumericVector& theta);
RcppExport SEXP _nlmixr2est_foceiOuterG(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiOuterG(theta));
    return rcpp_result_gen;
END_RCPP
}
// foceiOuter
Environment foceiOuter(Environment e);
RcppExport SEXP _nlmixr2est_foceiOuter(SEXP eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type e(eSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiOuter(e));
    return rcpp_result_gen;
END_RCPP
}
// nlmixr2Gill83_
List nlmixr2Gill83_(Function what, NumericVector args, Environment envir, LogicalVector which, double gillRtol, int gillK, double gillStep, double gillFtol, bool optGillF);
RcppExport SEXP _nlmixr2est_nlmixr2Gill83_(SEXP whatSEXP, SEXP argsSEXP, SEXP envirSEXP, SEXP whichSEXP, SEXP gillRtolSEXP, SEXP gillKSEXP, SEXP gillStepSEXP, SEXP gillFtolSEXP, SEXP optGillFSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type what(whatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type args(argsSEXP);
    Rcpp::traits::input_parameter< Environment >::type envir(envirSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type which(whichSEXP);
    Rcpp::traits::input_parameter< double >::type gillRtol(gillRtolSEXP);
    Rcpp::traits::input_parameter< int >::type gillK(gillKSEXP);
    Rcpp::traits::input_parameter< double >::type gillStep(gillStepSEXP);
    Rcpp::traits::input_parameter< double >::type gillFtol(gillFtolSEXP);
    Rcpp::traits::input_parameter< bool >::type optGillF(optGillFSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmixr2Gill83_(what, args, envir, which, gillRtol, gillK, gillStep, gillFtol, optGillF));
    return rcpp_result_gen;
END_RCPP
}
// nlmixr2Eval_
double nlmixr2Eval_(NumericVector theta, std::string md5);
RcppExport SEXP _nlmixr2est_nlmixr2Eval_(SEXP thetaSEXP, SEXP md5SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< std::string >::type md5(md5SEXP);
    rcpp_result_gen = Rcpp::wrap(nlmixr2Eval_(theta, md5));
    return rcpp_result_gen;
END_RCPP
}
// nlmixr2Unscaled_
RObject nlmixr2Unscaled_(NumericVector theta, std::string md5);
RcppExport SEXP _nlmixr2est_nlmixr2Unscaled_(SEXP thetaSEXP, SEXP md5SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< std::string >::type md5(md5SEXP);
    rcpp_result_gen = Rcpp::wrap(nlmixr2Unscaled_(theta, md5));
    return rcpp_result_gen;
END_RCPP
}
// nlmixr2Grad_
NumericVector nlmixr2Grad_(NumericVector theta, std::string md5);
RcppExport SEXP _nlmixr2est_nlmixr2Grad_(SEXP thetaSEXP, SEXP md5SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< std::string >::type md5(md5SEXP);
    rcpp_result_gen = Rcpp::wrap(nlmixr2Grad_(theta, md5));
    return rcpp_result_gen;
END_RCPP
}
// nlmixr2ParHist_
RObject nlmixr2ParHist_(std::string md5);
RcppExport SEXP _nlmixr2est_nlmixr2ParHist_(SEXP md5SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type md5(md5SEXP);
    rcpp_result_gen = Rcpp::wrap(nlmixr2ParHist_(md5));
    return rcpp_result_gen;
END_RCPP
}
// nlmixr2Hess_
RObject nlmixr2Hess_(RObject thetaT, RObject fT, RObject e, RObject gillInfoT);
RcppExport SEXP _nlmixr2est_nlmixr2Hess_(SEXP thetaTSEXP, SEXP fTSEXP, SEXP eSEXP, SEXP gillInfoTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type thetaT(thetaTSEXP);
    Rcpp::traits::input_parameter< RObject >::type fT(fTSEXP);
    Rcpp::traits::input_parameter< RObject >::type e(eSEXP);
    Rcpp::traits::input_parameter< RObject >::type gillInfoT(gillInfoTSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmixr2Hess_(thetaT, fT, e, gillInfoT));
    return rcpp_result_gen;
END_RCPP
}
// shi21CentralWrap
Rcpp::List shi21CentralWrap(Rcpp::Function f, arma::vec t, arma::vec f0, int idx, double ef);
RcppExport SEXP _nlmixr2est_shi21CentralWrap(SEXP fSEXP, SEXP tSEXP, SEXP f0SEXP, SEXP idxSEXP, SEXP efSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type f(fSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type f0(f0SEXP);
    Rcpp::traits::input_parameter< int >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< double >::type ef(efSEXP);
    rcpp_result_gen = Rcpp::wrap(shi21CentralWrap(f, t, f0, idx, ef));
    return rcpp_result_gen;
END_RCPP
}
// sqrtm
NumericMatrix sqrtm(NumericMatrix m);
RcppExport SEXP _nlmixr2est_sqrtm(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(sqrtm(m));
    return rcpp_result_gen;
END_RCPP
}
// foceiCalcCov
NumericMatrix foceiCalcCov(Environment e);
RcppExport SEXP _nlmixr2est_foceiCalcCov(SEXP eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type e(eSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiCalcCov(e));
    return rcpp_result_gen;
END_RCPP
}
// foceiFitCpp_
Environment foceiFitCpp_(Environment e);
RcppExport SEXP _nlmixr2est_foceiFitCpp_(SEXP eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type e(eSEXP);
    rcpp_result_gen = Rcpp::wrap(foceiFitCpp_(e));
    return rcpp_result_gen;
END_RCPP
}
// vaeInnerSetup_
RObject vaeInnerSetup_(Environment e);
RcppExport SEXP _nlmixr2est_vaeInnerSetup_(SEXP eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type e(eSEXP);
    rcpp_result_gen = Rcpp::wrap(vaeInnerSetup_(e));
    return rcpp_result_gen;
END_RCPP
}
// vaeInnerLik
List vaeInnerLik(NumericMatrix etaMat, int cores, bool grad, bool preds);
RcppExport SEXP _nlmixr2est_vaeInnerLik(SEXP etaMatSEXP, SEXP coresSEXP, SEXP gradSEXP, SEXP predsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type etaMat(etaMatSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    Rcpp::traits::input_parameter< bool >::type grad(gradSEXP);
    Rcpp::traits::input_parameter< bool >::type preds(predsSEXP);
    rcpp_result_gen = Rcpp::wrap(vaeInnerLik(etaMat, cores, grad, preds));
    return rcpp_result_gen;
END_RCPP
}
// vaeInnerFree_
RObject vaeInnerFree_();
RcppExport SEXP _nlmixr2est_vaeInnerFree_() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(vaeInnerFree_());
    return rcpp_result_gen;
END_RCPP
}
// boxCox_
NumericVector boxCox_(NumericVector x, double lambda, int yj);
RcppExport SEXP _nlmixr2est_boxCox_(SEXP xSEXP, SEXP lambdaSEXP, SEXP yjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type yj(yjSEXP);
    rcpp_result_gen = Rcpp::wrap(boxCox_(x, lambda, yj));
    return rcpp_result_gen;
END_RCPP
}
// iBoxCox_
NumericVector iBoxCox_(NumericVector x, double lambda, int yj);
RcppExport SEXP _nlmixr2est_iBoxCox_(SEXP xSEXP, SEXP lambdaSEXP, SEXP yjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type yj(yjSEXP);
    rcpp_result_gen = Rcpp::wrap(iBoxCox_(x, lambda, yj));
    return rcpp_result_gen;
END_RCPP
}
// nmNearPD_
RObject nmNearPD_(RObject x, bool keepDiag, bool do2eigen, bool doDykstra, bool only_values, double eig_tol, double conv_tol, double posd_tol, int maxit, bool trace);
RcppExport SEXP _nlmixr2est_nmNearPD_(SEXP xSEXP, SEXP keepDiagSEXP, SEXP do2eigenSEXP, SEXP doDykstraSEXP, SEXP only_valuesSEXP, SEXP eig_tolSEXP, SEXP conv_tolSEXP, SEXP posd_tolSEXP, SEXP maxitSEXP, SEXP traceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type keepDiag(keepDiagSEXP);
    Rcpp::traits::input_parameter< bool >::type do2eigen(do2eigenSEXP);
    Rcpp::traits::input_parameter< bool >::type doDykstra(doDykstraSEXP);
    Rcpp::traits::input_parameter< bool >::type only_values(only_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type eig_tol(eig_tolSEXP);
    Rcpp::traits::input_parameter< double >::type conv_tol(conv_tolSEXP);
    Rcpp::traits::input_parameter< double >::type posd_tol(posd_tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< bool >::type trace(traceSEXP);
    rcpp_result_gen = Rcpp::wrap(nmNearPD_(x, keepDiag, do2eigen, doDykstra, only_values, eig_tol, conv_tol, posd_tol, maxit, trace));
    return rcpp_result_gen;
END_RCPP
}
// nlmFree
RObject nlmFree();
RcppExport SEXP _nlmixr2est_nlmFree() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(nlmFree());
    return rcpp_result_gen;
END_RCPP
}
// nlmSetup
RObject nlmSetup(Environment e);
RcppExport SEXP _nlmixr2est_nlmSetup(SEXP eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type e(eSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmSetup(e));
    return rcpp_result_gen;
END_RCPP
}
// nlmScalePar
RObject nlmScalePar(RObject p0);
RcppExport SEXP _nlmixr2est_nlmScalePar(SEXP p0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type p0(p0SEXP);
    rcpp_result_gen = Rcpp::wrap(nlmScalePar(p0));
    return rcpp_result_gen;
END_RCPP
}
// nlmUnscalePar
NumericVector nlmUnscalePar(NumericVector p);
RcppExport SEXP _nlmixr2est_nlmUnscalePar(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmUnscalePar(p));
    return rcpp_result_gen;
END_RCPP
}
// nlmSolveR
double nlmSolveR(arma::vec& theta);
RcppExport SEXP _nlmixr2est_nlmSolveR(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmSolveR(theta));
    return rcpp_result_gen;
END_RCPP
}
// nlmerSolveGrad
RObject nlmerSolveGrad(arma::mat& thetaMat);
RcppExport SEXP _nlmixr2est_nlmerSolveGrad(SEXP thetaMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type thetaMat(thetaMatSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmerSolveGrad(thetaMat));
    return rcpp_result_gen;
END_RCPP
}
// nlmSetScaleC
RObject nlmSetScaleC(NumericVector scaleC);
RcppExport SEXP _nlmixr2est_nlmSetScaleC(SEXP scaleCSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type scaleC(scaleCSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmSetScaleC(scaleC));
    return rcpp_result_gen;
END_RCPP
}
// nlmGetScaleC
NumericVector nlmGetScaleC(arma::vec& theta, double to);
RcppExport SEXP _nlmixr2est_nlmGetScaleC(SEXP thetaSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type to(toSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmGetScaleC(theta, to));
    return rcpp_result_gen;
END_RCPP
}
// nlmSolveGradR
RObject nlmSolveGradR(arma::vec& theta);
RcppExport SEXP _nlmixr2est_nlmSolveGradR(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmSolveGradR(theta));
    return rcpp_result_gen;
END_RCPP
}
// solveGradNls
NumericVector solveGradNls(arma::vec& theta, int returnType);
RcppExport SEXP _nlmixr2est_solveGradNls(SEXP thetaSEXP, SEXP returnTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type returnType(returnTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(solveGradNls(theta, returnType));
    return rcpp_result_gen;
END_RCPP
}
// nlmSolveGradHess
RObject nlmSolveGradHess(arma::vec& theta);
RcppExport SEXP _nlmixr2est_nlmSolveGradHess(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmSolveGradHess(theta));
    return rcpp_result_gen;
END_RCPP
}
// nlmSolveSwitch
RObject nlmSolveSwitch(arma::vec& theta);
RcppExport SEXP _nlmixr2est_nlmSolveSwitch(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmSolveSwitch(theta));
    return rcpp_result_gen;
END_RCPP
}
// optimFunC
NumericVector optimFunC(arma::vec& theta, bool grad);
RcppExport SEXP _nlmixr2est_optimFunC(SEXP thetaSEXP, SEXP gradSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< bool >::type grad(gradSEXP);
    rcpp_result_gen = Rcpp::wrap(optimFunC(theta, grad));
    return rcpp_result_gen;
END_RCPP
}
// nlminbFunC
NumericVector nlminbFunC(arma::vec& theta, int type);
RcppExport SEXP _nlmixr2est_nlminbFunC(SEXP thetaSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(nlminbFunC(theta, type));
    return rcpp_result_gen;
END_RCPP
}
// nlmPrintHeader
RObject nlmPrintHeader();
RcppExport SEXP _nlmixr2est_nlmPrintHeader() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(nlmPrintHeader());
    return rcpp_result_gen;
END_RCPP
}
// nlmWarnings
RObject nlmWarnings();
RcppExport SEXP _nlmixr2est_nlmWarnings() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(nlmWarnings());
    return rcpp_result_gen;
END_RCPP
}
// nlmCensInfo
SEXP nlmCensInfo();
RcppExport SEXP _nlmixr2est_nlmCensInfo() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(nlmCensInfo());
    return rcpp_result_gen;
END_RCPP
}
// nlmGetParHist
RObject nlmGetParHist(bool p);
RcppExport SEXP _nlmixr2est_nlmGetParHist(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmGetParHist(p));
    return rcpp_result_gen;
END_RCPP
}
// nlmAdjustHessian
RObject nlmAdjustHessian(RObject Hin, arma::vec theta);
RcppExport SEXP _nlmixr2est_nlmAdjustHessian(SEXP HinSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type Hin(HinSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmAdjustHessian(Hin, theta));
    return rcpp_result_gen;
END_RCPP
}
// nlmAdjustCov
RObject nlmAdjustCov(RObject CovIn, arma::vec theta);
RcppExport SEXP _nlmixr2est_nlmAdjustCov(SEXP CovInSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type CovIn(CovInSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmAdjustCov(CovIn, theta));
    return rcpp_result_gen;
END_RCPP
}
// augPredTrans
RObject augPredTrans(NumericVector& pred, NumericVector& ipred, NumericVector& lambda, RObject& yjIn, NumericVector& low, NumericVector& hi);
RcppExport SEXP _nlmixr2est_augPredTrans(SEXP predSEXP, SEXP ipredSEXP, SEXP lambdaSEXP, SEXP yjInSEXP, SEXP lowSEXP, SEXP hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type ipred(ipredSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< RObject& >::type yjIn(yjInSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type low(lowSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type hi(hiSEXP);
    rcpp_result_gen = Rcpp::wrap(augPredTrans(pred, ipred, lambda, yjIn, low, hi));
    return rcpp_result_gen;
END_RCPP
}
// rxode2stateOde
SEXP rxode2stateOde(SEXP inp);
RcppExport SEXP _nlmixr2est_rxode2stateOde(SEXP inpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inp(inpSEXP);
    rcpp_result_gen = Rcpp::wrap(rxode2stateOde(inp));
    return rcpp_result_gen;
END_RCPP
}
// saem_do_pred
SEXP saem_do_pred(SEXP in_phi, SEXP in_evt, SEXP in_opt);
RcppExport SEXP _nlmixr2est_saem_do_pred(SEXP in_phiSEXP, SEXP in_evtSEXP, SEXP in_optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type in_phi(in_phiSEXP);
    Rcpp::traits::input_parameter< SEXP >::type in_evt(in_evtSEXP);
    Rcpp::traits::input_parameter< SEXP >::type in_opt(in_optSEXP);
    rcpp_result_gen = Rcpp::wrap(saem_do_pred(in_phi, in_evt, in_opt));
    return rcpp_result_gen;
END_RCPP
}
// saem_fit
SEXP saem_fit(SEXP xSEXP);
RcppExport SEXP _nlmixr2est_saem_fit(SEXP xSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xSEXP(xSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(saem_fit(xSEXP));
    return rcpp_result_gen;
END_RCPP
}
// nlmixr2Parameters
List nlmixr2Parameters(NumericVector theta, DataFrame eta);
RcppExport SEXP _nlmixr2est_nlmixr2Parameters(SEXP thetaSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmixr2Parameters(theta, eta));
    return rcpp_result_gen;
END_RCPP
}
// vaeEncoderFwdBwd
List vaeEncoderFwdBwd(arma::cube dataIn, IntegerVector lengths, arma::mat covIn, arma::mat eps, arma::mat Wih, arma::mat Whh, arma::vec bih, arma::vec bhh, arma::mat fcW, arma::vec fcB, int zDim, arma::mat gZ, arma::mat gLogSigmaDirect);
RcppExport SEXP _nlmixr2est_vaeEncoderFwdBwd(SEXP dataInSEXP, SEXP lengthsSEXP, SEXP covInSEXP, SEXP epsSEXP, SEXP WihSEXP, SEXP WhhSEXP, SEXP bihSEXP, SEXP bhhSEXP, SEXP fcWSEXP, SEXP fcBSEXP, SEXP zDimSEXP, SEXP gZSEXP, SEXP gLogSigmaDirectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type dataIn(dataInSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type lengths(lengthsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type covIn(covInSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Wih(WihSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Whh(WhhSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type bih(bihSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type bhh(bhhSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type fcW(fcWSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type fcB(fcBSEXP);
    Rcpp::traits::input_parameter< int >::type zDim(zDimSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type gZ(gZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type gLogSigmaDirect(gLogSigmaDirectSEXP);
    rcpp_result_gen = Rcpp::wrap(vaeEncoderFwdBwd(dataIn, lengths, covIn, eps, Wih, Whh, bih, bhh, fcW, fcB, zDim, gZ, gLogSigmaDirect));
    return rcpp_result_gen;
END_RCPP
}
// vaeFoceLik
List vaeFoceLik(arma::vec f0, arma::mat J0, arma::vec R, arma::vec y, arma::ivec cens, arma::vec limit, arma::mat zLin, arma::mat zPop, arma::vec omega, arma::ivec subjOffset, double Rscale, int adjLik, int maxit, double tol, int cores, int nMix, arma::vec mixProb);
RcppExport SEXP _nlmixr2est_vaeFoceLik(SEXP f0SEXP, SEXP J0SEXP, SEXP RSEXP, SEXP ySEXP, SEXP censSEXP, SEXP limitSEXP, SEXP zLinSEXP, SEXP zPopSEXP, SEXP omegaSEXP, SEXP subjOffsetSEXP, SEXP RscaleSEXP, SEXP adjLikSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP coresSEXP, SEXP nMixSEXP, SEXP mixProbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type f0(f0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type J0(J0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type cens(censSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type limit(limitSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type zLin(zLinSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type zPop(zPopSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type subjOffset(subjOffsetSEXP);
    Rcpp::traits::input_parameter< double >::type Rscale(RscaleSEXP);
    Rcpp::traits::input_parameter< int >::type adjLik(adjLikSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    Rcpp::traits::input_parameter< int >::type nMix(nMixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mixProb(mixProbSEXP);
    rcpp_result_gen = Rcpp::wrap(vaeFoceLik(f0, J0, R, y, cens, limit, zLin, zPop, omega, subjOffset, Rscale, adjLik, maxit, tol, cores, nMix, mixProb));
    return rcpp_result_gen;
END_RCPP
}

// validate (ensure exported C++ functions exist before calling them)
static int _nlmixr2est_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("List(*nlmixrExpandFdParNlme_)(CharacterVector,CharacterVector)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _nlmixr2est_RcppExport_registerCCallable() { 
    R_RegisterCCallable("nlmixr2est", "_nlmixr2est_nlmixrExpandFdParNlme_", (DL_FUNC)_nlmixr2est_nlmixrExpandFdParNlme__try);
    R_RegisterCCallable("nlmixr2est", "_nlmixr2est_RcppExport_validate", (DL_FUNC)_nlmixr2est_RcppExport_validate);
    return R_NilValue;
}
