#' Deparse a value so that evaluating it gives back the identical value
#' @param value value to deparse
#' @return deparsed string
#' @noRd
.deparseValue <- function(value) {
  .d <- deparse1(value)
  if (identical(tryCatch(eval(str2lang(.d)), error = function(e) NULL), value)) {
    return(.d)
  }
  # the default 15 significant digits do not always read back the same double
  deparse1(value, control = c("keepNA", "keepInteger", "niceNames", "showAttributes", "digits17"))
}

#' The `print = ` argument that rebuilds an `iterPrintControl()`
#' @param value the control's `iterPrintControl`
#' @return `print = <every>`, or `print = iterPrintControl(...)` when more than
#'   `every` differs from this session's default
#' @noRd
.deparseIterPrint <- function(value) {
  .def <- iterPrintControl()
  .w <- names(.def)[!vapply(names(.def), function(n) identical(.def[[n]], value[[n]]), logical(1))]
  if (identical(.w, "every")) {
    return(paste0("print = ", deparse1(value$every)))
  }
  paste0(
    "print = iterPrintControl(",
    paste(paste0(.w, " = ", vapply(.w, function(n) deparse1(value[[n]]), character(1))), collapse = ", "),
    ")"
  )
}

#' The default a control is deparsed against, built at the control's `sigdig`
#'
#' Tolerances derived from `sigdig` then match and are not written out.  A
#' control that does not keep `sigdig` (`saemControl()`) is taken to have been
#' built with `sigdig = sigdigTable` when that rebuilds its `rxControl`; the
#' default then carries the `"sigdig"` argument to write as an attribute.
#' @param default the constructor's default control
#' @param object the control being deparsed
#' @param ctor name of the constructor
#' @return the default control at the control's `sigdig`
#' @noRd
.deparseSigdigDefault <- function(default, object, ctor = class(default)[1]) {
  if (!any(c("sigdig", "...") %in% names(formals(ctor)))) {
    return(default)
  }
  .sig <- object[["sigdig"]]
  .kept <- !is.null(.sig)
  if (!.kept) {
    .sig <- object[["sigdigTable"]]
    if (
      is.null(.sig) || !isTRUE(object[["genRxControl"]]) || identical(object[["rxControl"]], default[["rxControl"]])
    ) {
      return(default)
    }
  } else if (identical(.sig, default[["sigdig"]])) {
    return(default)
  }
  .ret <- tryCatch(do.call(ctor, list(sigdig = .sig)), error = function(e) NULL)
  if (is.null(.ret) || (!.kept && !identical(.ret[["rxControl"]], object[["rxControl"]]))) {
    return(default)
  }
  if (!.kept) {
    attr(.ret, "sigdig") <- paste0("sigdig = ", .deparseValue(.sig))
  }
  .ret
}

.deparseShared <- function(x, value) {
  if (x == "iterPrintControl") {
    .deparseIterPrint(value)
  } else if (x == "rxControl") {
    .rx <- rxUiDeparse(value, "a")
    .rx <- .rx[[3]]
    paste0("rxControl = ", deparse1(.rx))
  } else if (x == "scaleType") {
    if (is.integer(value)) {
      paste0("scaleType =", deparse1(names(.scaleTypeIdx[which(value == .scaleTypeIdx)])))
    } else {
      paste0("scaleType =", deparse1(value))
    }
  } else if (x == "normType") {
    if (is.integer(value)) {
      paste0("normType =", deparse1(names(.normTypeIdx[which(value == .normTypeIdx)])))
    } else {
      paste0("normType =", deparse1(value))
    }
  } else if (x == "solveType") {
    if (is.integer(value)) {
      .solveTypeIdx <- c("hessian" = 3L, "grad" = 2L, "fun" = 1L)
      paste0("solveType =", deparse1(names(.solveTypeIdx[which(value == .solveTypeIdx)])))
    } else {
      paste0("solveType =", deparse1(value))
    }
  } else if (x == "eventType") {
    if (is.integer(value)) {
      .eventTypeIdx <- c("central" = 2L, "forward" = 1L, "forward" = 3L)
      paste0("eventType = ", deparse1(names(.eventTypeIdx[which(value == .eventTypeIdx)])))
    } else {
      paste0("eventType = ", deparse1(value))
    }
  } else if (x == "censMethod") {
    if (is.integer(value)) {
      .censMethodIdx <- c("truncated-normal" = 3L, "cdf" = 2L, "omit" = 1L, "pred" = 5L, "ipred" = 4L, "epred" = 6L)
      paste0("censMethod = ", deparse1(names(.censMethodIdx[which(value == .censMethodIdx)])))
    } else {
      paste0("censMethod = ", deparse1(value))
    }
  } else {
    NA_character_
  }
}

#' Identify Differences Between Standard and New Objects but used in rxUiDeparse
#'
#' Compares elements of a standard object against a new one so
#' `rxUiDeparse` only shows values that differ from the default.
#'
#' @param standard The standard object used for comparison. (for example `foceiControl()`)
#'
#' @param new The new object to be compared against the standard. This
#'   would be what the user supplide like
#'   `foceiControl(outerOpt="bobyqa")`
#' @param internal A character vector of element names to be ignored
#'   during the comparison. Default is an empty character
#'   vector. These are for internal items of the list that flag
#'   certain properties like if the `rxControl()` was generated by the
#'   `foceiControl()` procedure or not.
#' @return A vector of indices indicating which elements of the
#'   standard object differ from the new object.
#' @examples
#' standard <- list(a = 1, b = 2, c = 3)
#' new <- list(a = 1, b = 3, c = 3)
#' .deparseDifferent(standard, new)
#' @export
#' @keywords internal
#' @author Matthew L. Fidler
.deparseDifferent <- function(standard, new, internal = character(0)) {
  which(vapply(
    names(standard),
    function(x) {
      if (x %in% internal) {
        FALSE
      } else if (is.function(standard[[x]])) {
        warning(paste0("'", x, "' as a function not supported in ", class(standard), "() deparsing"), call. = FALSE)
        FALSE
      } else {
        !identical(standard[[x]], new[[x]])
      }
    },
    logical(1),
    USE.NAMES = FALSE
  ))
}

#' Deparse finalize a control or related object into a language object
#'
#' Deparses an object into a language expression, optionally using a
#' custom function for specific elements.
#'
#' @param default A default object used for comparison; This is the
#'   estimation control procedure.  It should have a class matching
#'   the function that created it.
#' @param object The object to be deparsed into a language expression
#' @param w A vector of indices indicating which elements are
#'   different and need to be deparsed. This likely comes from
#'   `.deparseDifferent()`
#' @param var A string representing the variable name to be assigned
#'   in the deparsed expression.
#' @param fun An optional custom function to handle specific elements
#'   during deparsing. Default is NULL. This handles things that are
#'   specific to an estimation control and is used by functions like
#'   `rxUiDeparse.saemControl()`
#' @param extra arguments written before the differing elements
#' @return A language object representing the deparsed expression.
#' @keywords internal
#' @author Matthew L. Fidler
#' @export
.deparseFinal <- function(default, object, w, var, fun = NULL, extra = character(0)) {
  .cls <- class(object)
  if (length(w) == 0 && length(extra) == 0) {
    return(str2lang(paste0(var, " <- ", .cls, "()")))
  }
  .retD <- vapply(
    names(default)[w],
    function(x) {
      .val <- .deparseShared(x, object[[x]])
      if (!is.na(.val)) {
        return(.val)
      }
      if (is.function(fun)) {
        .val <- fun(default, x, object[[x]])
        if (!is.na(.val)) {
          return(.val)
        }
      }
      paste0(x, "=", .deparseValue(object[[x]]))
    },
    character(1),
    USE.NAMES = FALSE
  )
  str2lang(paste(var, " <- ", .cls, "(", paste(c(extra, .retD), collapse = ","), ")"))
}

#' Deparse a control as a call to its constructor
#'
#' The body of the `rxUiDeparse()` methods of the estimation controls: the call
#' sets only what differs from the constructor's default.
#' @param object the control
#' @param var name the call is assigned to
#' @param default the control the constructor builds by default
#' @param internal names that are never deparsed
#' @param fun see [.deparseFinal()]
#' @return the language object `var <- <constructor>(...)`
#' @noRd
.deparseControl <- function(object, var, default, internal = "genRxControl", fun = NULL) {
  .default <- .deparseSigdigDefault(default, object)
  .w <- .deparseDifferent(.default, object, internal)
  if (!identical(object[["sigdig"]], default[["sigdig"]])) {
    .w <- sort(union(.w, which(names(.default) == "sigdig")))
  }
  .deparseFinal(.default, object, .w, var, fun = fun, extra = as.character(attr(.default, "sigdig")))
}
