# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cholSE_ <- function(A, tol) {
    .Call(`_nlmixr2est_cholSE_`, A, tol)
}

#' Expand Gradient for nlme
#'
#' @param state is the state to expand
#' @param params is the parameters to expand
#' @keywords internal
#' @noRd
nlmixrExpandFdParNlme_ <- function(state, vars) {
    .Call(`_nlmixr2est_nlmixrExpandFdParNlme_`, state, vars)
}

filterNormalLikeAndDoses <- function(inCmt, inDistribution, inDistCmt) {
    .Call(`_nlmixr2est_filterNormalLikeAndDoses`, inCmt, inDistribution, inDistCmt)
}

rxode2hasLlik <- function() {
    .Call(`_nlmixr2est_rxode2hasLlik`)
}

freeFocei <- function() {
    invisible(.Call(`_nlmixr2est_freeFocei`))
}

foceiInnerLp <- function(eta, id = 1L) {
    .Call(`_nlmixr2est_foceiInnerLp`, eta, id)
}

likInner <- function(eta, id = 1L) {
    .Call(`_nlmixr2est_likInner`, eta, id)
}

foceiLik <- function(theta) {
    .Call(`_nlmixr2est_foceiLik`, theta)
}

foceiOfv <- function(theta) {
    .Call(`_nlmixr2est_foceiOfv`, theta)
}

foceiNumericGrad <- function(theta) {
    .Call(`_nlmixr2est_foceiNumericGrad`, theta)
}

foceiSetup_ <- function(obj, data, theta, thetaFixed = NULL, skipCov = NULL, rxInv = NULL, lower = NULL, upper = NULL, etaMat = NULL, control = NULL) {
    .Call(`_nlmixr2est_foceiSetup_`, obj, data, theta, thetaFixed, skipCov, rxInv, lower, upper, etaMat, control)
}

foceiOuterF <- function(theta) {
    .Call(`_nlmixr2est_foceiOuterF`, theta)
}

foceiOuterG <- function(theta) {
    .Call(`_nlmixr2est_foceiOuterG`, theta)
}

foceiOuter <- function(e) {
    .Call(`_nlmixr2est_foceiOuter`, e)
}

nlmixr2Gill83_ <- function(what, args, envir, which, gillRtol, gillK = 10L, gillStep = 2, gillFtol = 0, optGillF = TRUE) {
    .Call(`_nlmixr2est_nlmixr2Gill83_`, what, args, envir, which, gillRtol, gillK, gillStep, gillFtol, optGillF)
}

#' @rdname nlmixr2GradFun
#' @export
nlmixr2Eval_ <- function(theta, md5) {
    .Call(`_nlmixr2est_nlmixr2Eval_`, theta, md5)
}

#' @rdname nlmixr2GradFun
#' @export
nlmixr2Unscaled_ <- function(theta, md5) {
    .Call(`_nlmixr2est_nlmixr2Unscaled_`, theta, md5)
}

#' @rdname nlmixr2GradFun
#' @export
nlmixr2Grad_ <- function(theta, md5) {
    .Call(`_nlmixr2est_nlmixr2Grad_`, theta, md5)
}

#' @rdname nlmixr2GradFun
#' @export
nlmixr2ParHist_ <- function(md5) {
    .Call(`_nlmixr2est_nlmixr2ParHist_`, md5)
}

nlmixr2Hess_ <- function(thetaT, fT, e, gillInfoT) {
    .Call(`_nlmixr2est_nlmixr2Hess_`, thetaT, fT, e, gillInfoT)
}

#' Return the square root of general square matrix A
#'
#' @param m Matrix to take the square root of.
#'
#' @return A square root general square matrix of m
#'
#' @export
sqrtm <- function(m) {
    .Call(`_nlmixr2est_sqrtm`, m)
}

foceiCalcCov <- function(e) {
    .Call(`_nlmixr2est_foceiCalcCov`, e)
}

#' Fit/Evaluate FOCEi
#'
#' This shouldn't be called directly.
#'
#' @param e Environment
#'
#' @return A focei fit object
#'
#' @keywords internal
#' @export
foceiFitCpp_ <- function(e) {
    .Call(`_nlmixr2est_foceiFitCpp_`, e)
}

boxCox_ <- function(x = 1L, lambda = 1, yj = 0L) {
    .Call(`_nlmixr2est_boxCox_`, x, lambda, yj)
}

iBoxCox_ <- function(x = 1L, lambda = 1, yj = 0L) {
    .Call(`_nlmixr2est_iBoxCox_`, x, lambda, yj)
}

nmNearPD_ <- function(x, keepDiag = FALSE, do2eigen = TRUE, doDykstra = TRUE, only_values = FALSE, eig_tol = 1e-6, conv_tol = 1e-7, posd_tol = 1e-8, maxit = 100L, trace = FALSE) {
    .Call(`_nlmixr2est_nmNearPD_`, x, keepDiag, do2eigen, doDykstra, only_values, eig_tol, conv_tol, posd_tol, maxit, trace)
}

augPredTrans <- function(pred, ipred, lambda, yjIn, low, hi) {
    .Call(`_nlmixr2est_augPredTrans`, pred, ipred, lambda, yjIn, low, hi)
}

saem_do_pred <- function(in_phi, in_evt, in_opt) {
    .Call(`_nlmixr2est_saem_do_pred`, in_phi, in_evt, in_opt)
}

saem_fit <- function(xSEXP) {
    .Call(`_nlmixr2est_saem_fit`, xSEXP)
}

nlmixr2Parameters <- function(theta, eta) {
    .Call(`_nlmixr2est_nlmixr2Parameters`, theta, eta)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_nlmixr2est_RcppExport_registerCCallable', PACKAGE = 'nlmixr2est')
})
